# Generated by Django 4.1.5 on 2023-04-02 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_remove_news_author_delete_comment_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_news', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.news', verbose_name='новость')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
